### PR TITLE
add shell support

### PR DESCRIPTION
**Pull request by robingoth**
I'm using zsh and run AWS CLI in a Docker container. `ssm-session` wasn't working for me, so I added shell support here

### CODE REVIEW

**Comment by mludvig** [comment]
Hey, thanks for the pull request. Does that mean that Python's `os.system()` doesn't work on zsh-based installations? That's odd...

**Comment by robingoth** [comment]
It is using `/bin/sh` by default as I understood

**Comment by mludvig** [comment]
Hey, can you try if the latest master version works for you? I have switched from os.system() to os.execvp() in 93d5b2a and I hope that it helped. Let me know plz. Thanks!

**Comment by mludvig** [comment]
Didn't hear back. I assume that it works.

**Pull request closed without merging**
